# docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: healthcare_app
    container_name: healthcare_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: healthcare_db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  dbdata:
